quartz:
  scheduler-name: QuartzScheduler
  properties:
    org:
      quartz:
        threadPool:
          threadCount: 5

spring:
  jdbc:
    template:
      fetch-size: 10000
      max-rows: 10000
  datasource:
    driver-class-name: com.tmax.tibero.jdbc.TbDriver
    url: jdbc:tibero:thin:@10.47.39.125:8629:DB_D_GMD
    username: GMDMO 
    password: gmdmo     
    sql-script-encoding: UTF-8
      
camel:
  springboot:
    main-run-controller: true
    stream-caching-enabled: true
    jmx-enabled: false
    shutdown-timeout: 1
  component:
    kafka:
      max-request-size: 10485760
      brokers: 10.47.39.124:9092,10.47.39.67:9092,10.47.39.125:9092
      shutdown-timeout: 1
      
logging:
  level:
    org.apache.camel.component.sql.DefaultSqlPrepareStatementStrategy: info #쿼리 보고 싶을 경우
    org.apache.kafka: warn
